# if you uncomment styles will dismatch, use correct link when in production
baseURL = '/' 
languageCode = 'en-us'
title = 'AdmStaff'
theme = 'adm'

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    identifier = "wiki"
    name = "wiki"
    url = "/wiki/"
    weight = 10
